### ISSUE TITLE
Create Excel File

### ISSUE THREAD

**Issue by WilliamHuang1995** [WilliamHuang1995/HearthStoneStats#1]
Determine how the excel layout should look like so that I can determine how the java file reads it
Let me know if you ever change the format. Or try not to change the format once it is finalized

**Comment by ghost** [comment]
The excel file consists of a dummy first line and other ";" separated lines that depict individual cards with attributes of name, cost, set, hero class, and rarity.
[cards.zip](https://github.com/WilliamHuang1995/HearthStoneStats/files/391722/cards.zip)
